sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended lmodern
  texlive-science texlive-math-extra texlive-xetex pgf
script:
- xelatex resume
deploy:
  provider: releases
  api_key:
    secure: cRquNUBq+i3VG73GFVmpELWBWn+jKjlT8Dx7dn+kQie4Mx2r2e5SZ93uX5/xVArrnqhKidD3N6pWPYpALYaSF5h1vtF/t7m7X9PzU+NiCVGYw+NRksczTgCJkMggf0EVLlue+MTWSWT3CO58pueWCVXGSepXv59vWNCtegW0sCeZnNNSAjxSbV83FiAL/n3hEQFUHBXqL8Mfmm+Cs6x8Zqz3PLXYH2Gjnupeouuz5KSq9pp/htXfiDVvvsZmotBLbfNfydsrzSQn7FRnMKuDzWSVI6JFH7Hh8Ls2RLj8RT+6n/bJZrcp7jI3eAKysKtMwHJTiZcFi+DnNkek0tI/5AmtIs6fRy9PH8tYr1HR3lEB4HpVCBGCh0k4E5cyOiwQiP50VxFjjYmPL98fQcs0AoC4GQLIdAC6kbKxsrJOFSSCa6O7j7sFspdiJB6a5YjG43Oq+MCq8w2Pk/t8fvVlKXCuBUWZK3HInFimLwvCwLMqk92/Z6a4e94bjnluR50yBK//fW+p/0xGr7m2Abo9IR9qwq8V5FyqnX3rR2BIokMv/NsEcvFWSVqHcnUMSQuTBCrO04W7cdYSt/+Rys78M6lu+8bbvbS7G4vVpCcK/8MXgtrdk1B0KUlYQohNdlQXCtM0ssxgFkYLKTbsqgbpEqTBW1JoIqgbvraSwJdhPWs=
  skip_cleanup: true
  file: resume.pdf
